[package]
name = "tinybook"
version = "0.1.0"
edition = "2024"
include = [
  "tinybook/**/*",
  "examples/**/*.rs"
]

[lib]
path = "tinybook/lib.rs"

[workspace]
members = ["examples"]

[workspace.dependencies]
tinybook = { path = "." }


